config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'games#index'
  post '/users', to: 'games#create_user'
  get '/answer', to: 'games#answer_round', as: :answer_round
  put '/answers/:id', to: 'answers#update', as: :update_answer
  get '/questions/:id/archived', to: 'games#archived_question', as: :archived_question
  get '/get_assessments', to: 'answers#get_assessment_path', as: :move_to_assessment
  get '/get_results', to: 'answers#get_result_path', as: :move_to_result
  resources :answers, only: :index do
    post :aggregate_points, on: :collection
    get :result, on: :collection
  end
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :bigint           not null, primary key
#  content     :string
#  total_point :integer
#  user_id     :integer          not null
#  question_id :integer          not null
#  status      :integer          default("active")
#  round       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :assessments

  enum status: { active: 0, archived: 1 }

  scope :with_round, -> (round) { where(round: round) }
  scope :ordered_answers_by_created_at, -> { order(:created_at) }
  scope :ordered_answers_by_point, -> { order(:point) }

  validates :content, presence: true, on: :update
  validates :content, length: { maximum: 140 }, allow_blank: true
  validates :question_id, uniqueness: { scope: %i(user_id round) }

  def update_point!(point, assessment_user)
    self.update!(total_point: total_point.to_i + point.to_i)
    self.assessments.create!(point: point, assessment_user_id: assessment_user.id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assessment.rb
# == Schema Information
#
# Table name: assessments
#
#  id                 :bigint           not null, primary key
#  point              :integer
#  assessment_user_id :integer          not null
#  answer_id          :integer          not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Assessment < ApplicationRecord
  belongs_to :answer

  scope :by_assessment_user_id, -> (assessment_user_id) {where(assessment_user_id: assessment_user_id)}
  scope :by_answer_id, -> (answer_id) {where(answer_id: answer_id)}
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id            :bigint           not null, primary key
#  content       :string           not null
#  status        :integer          default("inactive")
#  time_start    :datetime
#  current_round :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Question < ApplicationRecord
  has_many :answers

  enum status: { inactive: 0, active: 1, archived: 2 }

  scope :with_round, -> (round) { where(current_round: round) }

  class << self
    def find_or_create_active_question
      unless question = self.active.first
        max_round = self.maximum(:current_round)
        unless self.inactive.exists?
          self.update_all(status: 'inactive', current_round: max_round.to_i + 1)
        end
        question = self.inactive.sample
        question.update!(status: 'active', time_start: Time.now) if question
      end
      question
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  has_many :answers

  validates :name, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @active_question = Question.active.first
    @answers = @active_question.answers.active.with_round(@active_question.current_round)
      .ordered_answers_by_created_at
    @aggregated = Assessment.by_assessment_user_id(current_user.id).by_answer_id(@answers.pluck(:id)).exists?
  end

  def update
    current_answer = Answer.active.find_by(user_id: current_user.id, question_id: Question.active.first)
    if current_answer && current_answer.content.nil?
      current_answer.update(answer_params)
    else
      @message = '回答済みのお題を再度回答出来ません。'
    end
    respond_to do |format|
      format.js
    end
  end

  def get_assessment_path
    render json: { redirect: answers_path }
  end

  def get_result_path
    render json: { redirect: result_answers_path }
  end

  def aggregate_points
    # points param format: {points: {answer_id1: point1, answer_id2: point2, answer_id3: point3}}
    answer_ids = params[:points]&.keys
    if Assessment.by_assessment_user_id(current_user.id).by_answer_id(answer_ids).exists?
      @success = false
      @message = '採点が完了しました。'
    else
      (params[:points] || {}).each do |answer_id, point|
        answer = Answer.active.find_by_id(answer_id)
        next unless answer
        answer.update_point!(point, current_user)
      end
      @success = true
    end

    respond_to do |format|
      format.js
    end
  end

  def result
    @active_question = Question.active.first
    @points = @active_question.answers.active.pluck(:total_point).uniq.sort_by { |a| -a.to_i }
    @answers = @active_question.answers.active.with_round(@active_question.current_round).includes(:user)
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :check_user_exists, only: [:index]
  # Access to regist user screen
  def index
    count_joined_room_users
    @user = User.new
  end

  # Create new user and redirect to answer the question screen
  def create_user
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      active_question = find_or_create_active_question
      if (active_question.time_start + 4.minute) < Time.current
        redirect_to result_answers_path and return
      elsif (active_question.time_start + 2.minute) < Time.current
        redirect_to answers_path and return
      end
      redirect_to answer_round_path
    else
      flash[:error] = { user_login: @user.errors.messages }
      render :index, status: :unprocessable_entity
    end
  end

  # Display answer the question screen
  def answer_round
    active_question = Question.active.first
    active_question.update(time_start: Time.current) if active_question.time_start.nil?
    @answer = current_user.answers.active.find_by(round: active_question.current_round) || current_user.answers.create!(question: active_question, status: 'active', round: active_question.current_round)
  end

  # Archived a question, after finish display result screen
  def archived_question
    active_question = Question.active.first
    if active_question && params[:id].present? && active_question.id == params[:id].to_i
      active_question.archived!
      active_question.answers.active.update_all(status: 'archived')
      find_or_create_active_question
    end
    render json: { redirect: answer_round_path }
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end

  def count_joined_room_users
    active_question = Question.active.first
    @joined_room_users_count = active_question ? active_question.answers.active.with_round(active_question.current_round).count : 0
  end

  def find_or_create_active_question
    Question.find_or_create_active_question
  end

  def check_user_exists
    if current_user
      active_question = find_or_create_active_question
      if (active_question.time_start + 4.minute) < Time.current
        redirect_to result_answers_path and return
      elsif (active_question.time_start + 2.minute) < Time.current
        redirect_to answers_path and return
      end
      redirect_to answer_round_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_ranking_text_color
    { 0 => 'text-pink', 1 => 'text-blue' }
  end

  def set_screen_header_text
    { 'answer' => 'お題', 'assessment' => '採点', 'ranking' => '結果' }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return unless session[:user_id]
    User.find_by_id(session[:user_id])
  end
end

app/views/answers/aggregate_points.js.erb
<% unless @success %>
  console.log('<%= @message %>')
<% end %>

app/views/answers/index.html.erb
<%= javascript_include_tag "answer", "data-turbo-track": "reload", defer: true %>
<%= render partial: 'templates/header', locals: { question: @active_question, screen: 'assessment' } %>
<div class="row h-380 bg-gray overflow-y-auto">
  <div class="col-12 h-full position-relative">
    <div class="row">
      <div class="col-12 h-full">
        <div class="row flex-row-reverse align-items-center border-dashed py-2">
          <div class="col-2">
            <% start_time = (@active_question.time_start + 2.minute).to_i %>
            <%= render partial: 'templates/countdown', locals: { start_time: start_time, redirect_path: '/get_results' } %>
          </div>
          <div class="col-5 fs-5 fw-bold text-end">採点終了まで残り</div>
        </div>
        <% if @answers.any?{ |answer| answer.content != nil } %>
          <div class="row text-center mt-2">
            <div class="col-2 fw-bold">2点</div>
            <div class="col-2 fw-bold">1点</div>
          </div>
        <% end %>
        <div class="row">
          <div class="col-12">
            <%= form_with url: aggregate_points_answers_path, method: :post, html: { remote: true, screen: 'assessment', is_answered: @aggregated }, authenticity_token: true do |f| %>
              <% @answers.each do |answer| %>
                <% unless answer.content.nil? %>
                  <div class="row pb-3  align-items-center">
                    <div class="col-2 text-center">
                      <input type="radio" name="points[<%= answer.id %>]" value="2" class="form-check-input fs-5 points" <%= 'checked' if answer.assessments.by_assessment_user_id(current_user.id).first&.point == 2 %>>
                    </div>
                    <div class="col-2 text-center">
                      <input type="radio" name="points[<%= answer.id %>]" value="1" class="form-check-input fs-5 points" <%= 'checked' if answer.assessments.by_assessment_user_id(current_user.id).first&.point == 1 %>>
                    </div>
                    <div class="col-8 py-3 border-dashed text-right text-break answer_content pre-whitespace" answer_id="<%= answer.id %>" answer_point="<%= answer.assessments&.first&.point %>"><%= answer.content %></div>
                  </div>
                <% end %>
              <% end %>
              <%= f.submit 'submit', class: 'form-submit-button d-none' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'templates/footer', locals: { button_text: '採点する' } %>

app/views/answers/result.html.erb
<%= render partial: 'templates/header', locals: { question: @active_question, screen: 'ranking' } %>
<div class="row h-420 bg-gray overflow-y-auto">
  <div class="col-12 h-full position-relative">
    <div class="row flex-row-reverse align-items-center border-dashed py-2">
      <div class="col-3">
        <% start_time = (@active_question.time_start + 4.minute).to_i %>
        <%= render partial: 'templates/countdown', locals: { start_time: start_time, redirect_path: "/questions/#{@active_question.id}/archived" } %>
      </div>
      <div class="col-5 fs-5 fw-bold">次のお題まで残り</div>
    </div>
    <div class="row">
      <div class="col-12">
        <% @points.each_with_index do |point, index| %>
          <div class="col-12 border-dashed py-3">
            <div class="row align-items-center fw-bold">
              <div class="col-2 fs-5 text-end <%= set_ranking_text_color[index] %>"><%= index + 1 %>位</div>
              <div class="col-10 p-0">(<%= point.to_i %>ポイント)</div>
            </div>
            <% @answers.to_a.select{|answer| answer.total_point == point}.each do |answer| %>
              <% unless answer.content.nil? %>
                <div class="row justify-content-center mt-2">
                  <div class="col-8 text-break pre-whitespace">
                    <%= answer&.content %>
                  </div>
                </div>
                <div class="row flex-row-reverse">
                  <div class="col-4">
                    <%= answer&.user.name %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if Rails.env.production? %>
  <div class="row"><%= render 'layouts/shared/google_ads' %></div>
<% end %>

app/views/answers/update.js.erb
<% unless @message.nil? %>
  $('.submit-button').attr('disabled', true).text('<%= @message %>');
<% end %>

app/views/games/answer_round.html.erb
<%= javascript_include_tag "answer", "data-turbo-track": "reload", defer: true %>
<%= render partial: 'templates/header', locals: { question: @answer.question, screen: 'answer' } %>
<div class="row h-380 bg-gray">
  <div class="col-12 position-relative">
    <div class="row">
      <div class="col-12">
        <div class="row">
          <p class="fs-4 fw-bold px-5 pt-4">採点まで残り</p>
        </div>
        <% start_time = @answer.question.time_start.to_i %>
        <%= render partial: 'templates/countdown', locals: { start_time: start_time, redirect_path: '/get_assessments' } %>
        <%= form_for @answer, url: update_answer_path(@answer), method: :put, remote: true, authenticity_token: true, html: { class: 'row justify-content-center mt-4', is_answered: !@answer.content.nil?, screen: 'answer' } do |f| %>
          <div class="col-11 col-sm-10 col-lg-8">
            <%= f.text_area :content, class: 'form-control', rows: 7 %>
            <input type="hidden" id="content" value="<%= @answer&.content %>">
            <div class="error text-center fw-bold text-danger mt-2"></div>
            <%= f.submit 'submit', class: 'form-submit-button d-none' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'templates/footer', locals: { button_text: '回答する' } %>

app/views/games/index.html.erb
<div class="row h-500 justify-content-center align-content-center bg-blue">
  <%= form_for @user, html: { class: 'col-8' } do |f| %>
    <h1 class="text-center fw-bold text-white mb-4">HATA</h1>
    <div class="mb-3">
      <%= f.text_field :name, class: 'form-control form-control-lg py-3', placeholder: 'ユーザー名' %>
      <% flash.each do |type, msg| %>
        <p class="mt-2 text-danger"><%= msg[:user_login][:name][0] if !msg[:user_login].nil? %></p>
      <% end %>
    </div>
    <%= f.submit '入室する', class: 'form-control form-control-lg py-3 bg-dark-blue text-white' %>
  <% end %>
  <div class="row justify-content-center mt-4">
    <div class="col-8">
      <p class="text-white d-flex justify-content-end mx-3">
        <span class="fs-2 mx-1"><%= @joined_room_users_count %></span>
        <span class="align-self-center">人が入室中</span>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hata</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container-fluid h-screen">
      <div class="container h-full">
        <div class="main-content row justify-content-center h-full">
          <div class="col-12 col-md-8 col-lg-6">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/shared/_google_ads.html.erb
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8967129057333443"
crossorigin="anonymous"></script>
<!-- 記事中 -->
<ins class="adsbygoogle google-ads-main-content"
style="display:block"
data-ad-client="ca-pub-8967129057333443"
data-ad-slot="7050831265"
data-ad-format="auto"
data-full-width-responsive="true"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/templates/_countdown.html.erb
<div class="row">
  <%= content_tag(:div, "Start!", class: 'text-center fs-3 fw-bold', data: {
    controller: "countdown",
    countdown_target: "countdown",
    start_time_value: start_time,
    redirect_path_value: redirect_path
  }) %>
</div>

app/views/templates/_footer.html.erb
<div class="row">
  <button class="submit-button col-12 bg-dark-blue text-white fw-bold fs-4 py-2 btn rounded-0"><%= button_text %></button>
</div>

app/views/templates/_header.html.erb
<div class="row">
  <div class="col-2 d-flex justify-content-center <%= screen.include?('answer') ? 'bg-blue' : 'bg-pink' %> py-3">
    <div class="row align-content-center ">
      <p class="text-center m-0 text-white fs-5 fw-bold"><%= set_screen_header_text[screen] %></p>
    </div>
  </div>
  <div class="col-10 bg-dark-blue py-3">
    <p class="m-0 text-white fs-5 fw-bold"><%= question.content %></p>
  </div>
</div>